kind: pipeline
type: docker
name: build-test-deploy

steps:
  - name: build
    image: maven:3.8.5-openjdk-17
    commands:
      - mvn clean install

  - name: test
    image: maven:3.8.5-openjdk-17
    commands:
      - mvn test

  - name: docker_build_and_push
    image: plugins/docker
    settings:
      repo: username/facturx-microservice
      tags: latest
      username:
        from_secret: facturx_user
      password:
        from_secret: facturx_secret