kind: pipeline
type: docker
name: pre-prod

steps:
  - name: build project
    image: maven:3.8.3-openjdk-17
    commands:
      - mvn clean install
  - name: build & publish docker image
    image: plugins/docker
    settings:
      dockerfile: ./Dockerfile
      username:
        from_secret: registry_username
      password:
        from_secret: registry_password
      repo: registry.marynsoft.com/r-d/facturx
      registry: registry.marynsoft.com
      insecure: true
      tags:
        - latest
  - name: Deploy
    image: appleboy/drone-ssh
    settings:
      host: 10.0.20.14
      username:
        from_secret: ssh_user
      password:
        from_secret: ssh_password
      port: 22
      script:
        - cd app
        - docker-compose pull
        - docker-compose up -d
# volumes:
# - name: cache
#   host:
#     path: /var/docker/drone/cache/backend
trigger:
  branch:
    - master
  event:
    - push